services:
  postgres:
    image: 'postgres:17-alpine'
    environment:
      - 'POSTGRES_DB=bookify'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=bookify'
    ports:
      - '50253:5432'
